apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node-app
  name: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  strategy: {}
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - image: sathyap04/nodejs:v1
        imagePullPolicy: Always
        name: nodejs-sample
      # imagePullSecrets:
      # - name: regcred                             
      serviceAccount: image-push-sa 