name: Build-And-Deploy
on:
  push:
    branches: [ master ]
  release:
    types:
      - prereleased
      - released
      - edited
  pull_request:
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: debianmaster/set-gitref-env@master
    - name: debug
      run: |
        echo $RELEASE_TAG
  build:
    runs-on: ubuntu-latest
    if: github.event.action != 'released'
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      name: publish-image
      with:
        repository: debianmaster/wel
        tag_with_ref: true
        registry: docker.io
        username: debianmaster
        password: ${{secrets.HUB_DEBIANMASTER}}
